I0314 11:05:16.844322 2596522 config.py:54] PyTorch version 2.1.1 available.
Loading checkpoint shards:   0%|          | 0/6 [00:00<?, ?it/s]Loading checkpoint shards:  17%|█▋        | 1/6 [00:00<00:00,  8.46it/s]Loading checkpoint shards:  33%|███▎      | 2/6 [00:00<00:00,  9.14it/s]Loading checkpoint shards:  67%|██████▋   | 4/6 [00:00<00:00,  9.83it/s]Loading checkpoint shards: 100%|██████████| 6/6 [00:00<00:00, 10.15it/s]Loading checkpoint shards: 100%|██████████| 6/6 [00:00<00:00,  9.90it/s]
I0314 11:05:18.647963 2596522 quantize_finetune_llama.py:142] loaded model
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/Weight_compression/comp_lm_qtip/quantize_llama/quantize_finetune_llama.py", line 248, in <module>
    main(args)
  File "/workspace/Weight_compression/comp_lm_qtip/quantize_llama/quantize_finetune_llama.py", line 146, in main
    with open(config, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../NWC/checkpoint/nwc/block_seq_row_16/lmbda100000_*/config.json'
