I0317 15:21:36.673484 3963593 config.py:54] PyTorch version 2.6.0 available.
W0317 15:21:36.953895 3963593 warnings.py:109] /opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/opt/conda/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

W0317 15:21:37.833457 3963593 warnings.py:109] /opt/conda/lib/python3.10/site-packages/compressai/models/video/google.py:353: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @amp.autocast(enabled=False)

Loading checkpoint shards:   0%|          | 0/7 [00:00<?, ?it/s]Loading checkpoint shards:  14%|█▍        | 1/7 [00:00<00:00,  7.03it/s]Loading checkpoint shards:  29%|██▊       | 2/7 [00:00<00:00,  7.66it/s]Loading checkpoint shards:  43%|████▎     | 3/7 [00:00<00:00,  7.95it/s]Loading checkpoint shards:  57%|█████▋    | 4/7 [00:00<00:00,  8.11it/s]Loading checkpoint shards:  71%|███████▏  | 5/7 [00:00<00:00,  8.23it/s]Loading checkpoint shards:  86%|████████▌ | 6/7 [00:00<00:00,  8.10it/s]Loading checkpoint shards: 100%|██████████| 7/7 [00:00<00:00,  7.96it/s]Loading checkpoint shards: 100%|██████████| 7/7 [00:00<00:00,  7.95it/s]
I0317 15:21:39.288317 3963593 quantize_finetune_llama.py:144] loaded model
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/Weight_compression/comp_lm_qtip/quantize_llama/quantize_finetune_llama.py", line 263, in <module>
    main(args)
  File "/workspace/Weight_compression/comp_lm_qtip/quantize_llama/quantize_finetune_llama.py", line 148, in main
    with open(config, 'r', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../NWC/checkpoint/nwc/block_seq_scaler_meta-llama--Meta-Llama-3-8B__col_4096_RHT.pt/lmbda10000_*/config.json'
